plugins:
  disorder_enabled:
    default: false
    client: true
  disorder_inference_service_api_endpoint:
    default: 'localhost'
  disorder_inference_service_api_model:
    type: enum
    default: unbiased
    choices:
      - unbiased
      - multilingual
      - original